[phases.setup]
nixPkgs = ["flutter", "python3", "git"]
env = { FLUTTER_VERSION = "3.32.8", FLUTTER_WEB_USE_SKIA = "true" }

[phases.install]
cmds = [
  "flutter doctor -v",
  "flutter config --enable-web",
  "flutter --version",
  "flutter pub get"
]

[phases.build]
cmds = [
  "flutter clean",
  "flutter pub get",
  "flutter build web --release --web-renderer html --no-tree-shake-icons"
]

[start]
cmd = "cd build/web && python3 -m http.server $PORT" 