[phases.setup]
nixPkgs = ["flutter", "python3", "git"]

[phases.install]
cmds = [
  "flutter doctor -v",
  "flutter config --enable-web",
  "flutter --version",
  "flutter pub get"
]

[phases.build]
cmds = [
  "flutter build web --release"
]

[start]
cmd = "cd build/web && python3 -m http.server $PORT" 