[phases.setup]
nixPkgs = ["flutter", "python3"]

[phases.install]
cmds = [
  "flutter config --enable-web",
  "flutter pub get"
]

[phases.build]
cmds = ["flutter build web --release"]

[start]
cmd = "cd build/web && python3 -m http.server $PORT" 