[phases.setup]
nixPkgs = ["flutter", "python3", "git"]

[phases.install]
cmds = [
  "flutter doctor",
  "flutter config --enable-web",
  "flutter pub get"
]

[phases.build]
cmds = ["flutter build web --release"]

[start]
cmd = "python3 -m http.server $PORT"
workDir = "build/web" 