[build]
builder = "nixpacks"

[deploy]
startCommand = "cd build/web && python3 -m http.server $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 