[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300
numReplicas = 1

[deploy.envs]
PORT = "8080" 